---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-loki
  namespace: logging
  labels:
    app: loki
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
...
