{
 "title": "Node Exporter Full",
 "tags": [ "linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$node\",job=\"$job\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"} - node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s", "label": "time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [5m])",
       "legendFormat": "{{device}} - Time spent doing I/Os"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      },
      {
       "expr": "node_memory_ShmemHugePages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "ShmemHugePages - Memory used by shared memory (shmem) and tmpfs allocated  with huge pages"
      },
      {
       "expr": "node_memory_ShmemPmdMapped_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "ShmemPmdMapped - Ammount of shared (shmem/tmpfs) memory backed by huge pages"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Kernel / CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      },
      {
       "expr": "node_memory_Percpu_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PerCPU - Per CPU memory allocated dynamically by loadable modules"
      }
     ]
    },
    {
     "title": "Memory HugePages Counter",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short", "label": "pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "Memory HugePages Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "Memory DirectMap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    },
    {
     "title": "Memory NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    }
   ]
  },
  {
   "title": "System Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "decbytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_max_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      },
      {
       "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "irate(process_virtual_memory_max_bytes{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "forks / sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_forks_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Process schedule stats Running / Waiting",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_schedstat_running_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
      },
      {
       "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "s", "label": "time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read time"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Write time"
      }
     ]
    },
    {
     "title": "Disk IOs Weighted",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "s", "label": "time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO time weighted"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "s", "label": "time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO time"
      },
      {
       "expr": "irate(node_disk_discard_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - discard time"
      }
     ]
    },
    {
     "title": "Disk IOs Current in Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 132 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
     "yaxes": [
      { "format": "short", "label": "file nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "short", "label": "files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 153 },
     "yaxes": [
      { "format": "short", "label": "file Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly / Error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      },
      {
       "expr": "node_filesystem_device_error{instance=\"$node\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
       "legendFormat": "{{mountpoint}} - Device error"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 194 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 194 },
     "yaxes": [
      { "format": "short", "label": "entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 204 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }} - Speed"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 204 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_mtu_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }} - Bytes"
      }
     ]
    },
    {
     "title": "Softnet Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 214 },
     "yaxes": [
      {
       "format": "short",
       "label": "packetes drop (-) / process (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(node_softnet_processed_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{cpu}} - Processed"
      },
      {
       "expr": "irate(node_softnet_dropped_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{cpu}} - Dropped"
      }
     ]
    },
    {
     "title": "Network Operational Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 214 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_network_up{operstate=\"up\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{interface}} - Operational state UP"
      },
      {
       "expr": "node_network_carrier{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}} - Physical link state"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape success"
      },
      {
       "expr": "node_textfile_scrape_error{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
      }
     ]
    }
   ]
  }
 ]
}