---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  type: ClusterIP  
  ports:
    - port: 8080
      targetPort: 8080
