---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.11.1.51-10.11.1.59
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-pool
  namespace: metallb-system
  ipAddressPools:
  - homelab-pool
...
