{
 "title": "Bandwidth",
 "tags": [
  "lisenet",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Download speed",
     "query": "SELECT download/1024/1024 FROM speedtest WHERE $timeFilter "
    },
    {
     "alias": "Upload speed",
     "query": "SELECT upload/1024/1024 FROM speedtest WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Ping",
     "query": "SELECT ping FROM speedtest WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Bytes Received/Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Bytes received",
     "query": "SELECT bytes_received/1024/1024 FROM speedtest WHERE $timeFilter"
    },
    {
     "alias": "Bytes sent",
     "query": "SELECT bytes_sent/1024/1024 FROM speedtest WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(bytes_received)/1024/1024 FROM speedtest WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(bytes_sent)/1024/1024 FROM speedtest WHERE $timeFilter"
    }
   ]
  }
 ]
}